// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HRStpEmployee.Models;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> HrstpEmployees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeGuid);

            entity.ToTable("HRStpEmployee");

            entity.Property(e => e.EmployeeGuid)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("EmployeeGUID");
            entity.Property(e => e.DateofBirth).HasColumnType("datetime");
            entity.Property(e => e.EmployeeCode).HasMaxLength(255);
            entity.Property(e => e.FlfirstName)
                .HasMaxLength(255)
                .HasColumnName("FLFirstName");
            entity.Property(e => e.FlfourthName)
                .HasMaxLength(255)
                .HasColumnName("FLFourthName");
            entity.Property(e => e.FlsecondName)
                .HasMaxLength(255)
                .HasColumnName("FLSecondName");
            entity.Property(e => e.FlthirdName)
                .HasMaxLength(255)
                .HasColumnName("FLThirdName");
            entity.Property(e => e.GenderGuid)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("GenderGUID");
            entity.Property(e => e.SlfirstName)
                .HasMaxLength(255)
                .HasColumnName("SLFirstName");
            entity.Property(e => e.SlfourthName)
                .HasMaxLength(255)
                .HasColumnName("SLFourthName");
            entity.Property(e => e.SlsecondName)
                .HasMaxLength(255)
                .HasColumnName("SLSecondName");
            entity.Property(e => e.SlthirdName)
                .HasMaxLength(255)
                .HasColumnName("SLThirdName");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}