// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace HRStpEmployee.Models;

public partial class Employee
{


    [Key]
    public string EmployeeGuid { get; set; }

    public string EmployeeCode { get; set; }

    public string FlfirstName { get; set; }

    public string FlsecondName { get; set; }

    public string FlthirdName { get; set; }

    public string FlfourthName { get; set; }

    public string SlfirstName { get; set; }

    public string SlsecondName { get; set; }

    public string SlthirdName { get; set; }
    public string SlfourthName { get; set; }


    [DataType(DataType.Date)]

    public DateTime? DateofBirth { get; set; }

    public string GenderGuid { get; set; }

    public string EnglishFullName { get; set; }

    public string ArabicFullName { get; set; }
}